name: Release to Maven Central
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Set release version
        run: |
          mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}

      - name: Publish package
        run: |
          mvn -P release --batch-mode deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}

      - name: Tag and commit release
        run: |
          git config --global user.email ${{ github.event.release.author.login }}@users.noreply.github.com
          git config --global user.name ${{ github.event.release.author.login }}
      
          ARTIFACT_ID=$(mvn -q help:evaluate -Dexpression=project.artifactId -DforceStdout)
          
          git commit -a -m "Release ${ARTIFACT_ID}-${{ github.event.release.tag_name }}"
          git tag -f "${ARTIFACT_ID}-${{ github.event.release.tag_name }}"

          mvn versions:set -DgenerateBackupPoms=false -DnextSnapshot
          NEXT_VERSION=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)
          
          git commit -a -m "[skip ci] ${ARTIFACT_ID}-${NEXT_VERSION}"
          
          git push
